=== albertogcatalan/daw1/xml/temperaturas/tiempo.dtd
<!ELEMENT informe (fecha, hora, zona, mediciones)>

<!ELEMENT fecha (#PCDATA)>
<!ELEMENT hora (#PCDATA)>
<!ELEMENT zona (ciudad, region, pais)>
<!ELEMENT ciudad (#PCDATA)>
<!ELEMENT region (#PCDATA)>
<!ELEMENT pais (#PCDATA)>
<!ELEMENT mediciones (cielo, temperatura, viento)>
<!ELEMENT cielo (#PCDATA)>
<!ELEMENT temperatura (#PCDATA)>
<!ELEMENT viento (direccion, velocidad)>
<!ELEMENT direccion (#PCDATA)>
<!ELEMENT velocidad (#PCDATA)>
<!ELEMENT temperatura escala CDATA>

=== albertogcatalan/daw1/xml/temperaturas/temperatura.xml
<?xml version="1.0" encoding="utf-8"?>
<!-- prólogo del documento -->
<!DOCTYPE informe SYSTEM "tiempo.dtd">
<informe>
	<fecha>9 de enero de 2012</fecha>
	<hora>10:00</hora>
	<zona>
		<ciudad>Zaragoza</ciudad>
		<region>Aragón</region>
		<pais>España</pais>
	</zona>
	<mediciones>
		<cielo>despejado</cielo>
		<temperatura escala="C">8</temperatura>
		<viento>
			<direccion>NW</direccion>
			<velocidad>5</velocidad>
		</viento>
	</mediciones>
</informe>
