=== albertogcatalan/daw1/xml/libreria virtual/libreria.dtd
<!ELEMENT autor ( #PCDATA ) >
<!ELEMENT descuento EMPTY >
<!ATTLIST descuento cantidad CDATA #REQUIRED >
<!ELEMENT disponible EMPTY >
<!ATTLIST disponible tiempo CDATA #REQUIRED >
<!ATTLIST disponible unidad CDATA #REQUIRED >
<!ELEMENT enlacelibro EMPTY >
<!ATTLIST enlacelibro href CDATA #REQUIRED >
<!ELEMENT formato ( #PCDATA ) >
<!ELEMENT libro ( titulo | disponible | autor | formato |
publicacion | precio | descuento | enlacelibro )* >
<!ELEMENT precio EMPTY >
<!ATTLIST precio cantidad CDATA #REQUIRED >
<!ATTLIST precio moneda CDATA #REQUIRED >
<!ELEMENT publicacion ( #PCDATA ) >
<!ELEMENT titulo ( #PCDATA ) >

=== albertogcatalan/daw1/xml/libreria virtual/libros.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- libreria virtual -->
<!DOCTYPE libro SYSTEM "libreria.dtd">
<libro>
  <titulo>El prisionero del cielo</titulo>
  <disponible tiempo="10" unidad="1"></disponible>
  <autor>Carlos Ruiz Zafón</autor>
  <formato>Libro</formato>
  <publicacion>11/2011</publicacion>
  <precio cantidad="21" moneda="EUR"></precio>
  <descuento cantidad="3"></descuento>
  <enlacelibro href="http://www.fnac.es/"></enlacelibro>
</libro>
